### ISSUE TITLE
OSError Traceback

### ISSUE THREAD

**Issue by Jimmy-Tsai** [sfarrens/sf_deconvolve#3]
Hi！There is an issue that when I run the code in  "sparse" or "all" mode，it would raise such a problem shows  

`Traceback (most recent call last):
  File "sf_deconvolve.py", line 221, in main
    run_script(log)
  File "sf_deconvolve.py", line 158, in run_script
    **vars(opts))
  File "/home/jumtsai/Desktop/sf_deconvolve-master/lib/deconvolve.py", line 529, in run
    kwargs = set_linear_op(data, **kwargs)
  File "/home/jumtsai/Desktop/sf_deconvolve-master/lib/deconvolve.py", line 117, in set_linear_op
    kwargs['linear_op'] = LinearCombo([Wavelet(data, wavelet_opt),
  File "/home/jumtsai/Desktop/sf_deconvolve-master/lib/linear.py", line 91, in __init__
    self.filters = get_mr_filters(self.data_shape, opt=wavelet_opt)
  File "/home/jumtsai/Desktop/sf_deconvolve-master/lib/wavelet.py", line 104, in get_mr_filters
    mr_filters = call_mr_transform(fake_data, opt=opt)
  File "/home/jumtsai/Desktop/sf_deconvolve-master/lib/wavelet.py", line 61, in call_mr_transform
    check_call(['mr_transform'] + opt + [file_fits, file_mr])
  File "/usr/lib/python2.7/subprocess.py", line 536, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory`
in the output log file.But when I set the mode as "lowr or "grad",the program would work without any problem.It's troubling me.I couldn't appreciate anymore if you can help me work out the issue.Thanks!

**Comment by sfarrens** [comment]
Hi Jimmy! 

Have you installed iSAP? 

To run the code using the sparsity option you will need a code called `mr_transform` from iSAP which performs the wavelet transformations. sf_deconvolve simply calls this binary from the system.

- You can download iSAP here: http://www.cosmostat.org/software/isap
- You will only need to compile the binaries in /cxx/sparse2d
- Make sure you update your path to find these binaries

Let me know if you have any issues with any of these steps.

Cheers,
Sam

**Comment by Jimmy-Tsai** [comment]
I'm so sorry that I forgot to read the doc before run your program.Then I download IDL 8.2,however,I followed the step on their website but the MAC address can not be changed on my Ubuntu16.04 system.Now I have not solved it yet.Thanks a lot!

**Comment by Jimmy-Tsai** [comment]
I'm so sorry that I forgot to read the doc before run your program.Then I download IDL 8.2,however,I followed the step on their website but the MAC address can not be changed on my Ubuntu16.04 system.Now I have not solved it yet.Thanks a lot!

**Comment by Jimmy-Tsai** [comment]
I'm so sorry that I forgot to read the doc before run your program.Then I download IDL 8.2,however,I followed the step on their website but the MAC address can not be changed on my Ubuntu16.04 system.Now I have not solved it yet.Thanks a lot!
