### ISSUE TITLE
__init__() got an unexpected keyword argument 'max_value'

### ISSUE THREAD

**Issue by mooneyse** [sfarrens/sf_deconvolve#5]
Hi,

I was trying out this and it crashed. Any idea why? Image and PSF look fine. Log below. Thanks!

```
01/07/2020 16:34:24 The log file has been set-up.
01/07/2020 16:34:24  Running SF_DECONVOLVE
01/07/2020 16:34:25  - Not all PSFs integrate to 1.0.
01/07/2020 16:34:25  - Input File: mysource.npy
01/07/2020 16:34:25  - PSF File: mypsf.npy
01/07/2020 16:34:25  - Mode: lowr
01/07/2020 16:34:25  - PSF Type: fixed
01/07/2020 16:34:25  - Gradient Type: psf_known
01/07/2020 16:34:25  - Convolution Method: astropy
01/07/2020 16:34:25  - Optimisation: condat
01/07/2020 16:34:25  - Positivity: True
01/07/2020 16:34:25  - Number of Reweightings: 1
01/07/2020 16:34:25  - Number of Iterations: 150
01/07/2020 16:34:25  - Cost Function Window: 1
01/07/2020 16:34:25  - Convergence Tolerance: 0.0003
01/07/2020 16:34:25  - Suppress Plots:False
01/07/2020 16:34:25  - Low Rank Threshold Factor: 1
01/07/2020 16:34:25  - Low Rank Threshold Type: hard
01/07/2020 16:34:25  - Low Rank Type: standard
01/07/2020 16:34:25  - Noise Estimate: 0.000105908768969
01/07/2020 16:34:34  - Spectral Radius: 0.999962382463
01/07/2020 16:34:34  - tau: 0.5
01/07/2020 16:34:34  - sigma: 0.5
01/07/2020 16:34:34  - rho: 0.8
01/07/2020 16:34:34  - 1/tau - sigma||L||^2 >= beta/2: True
01/07/2020 16:34:34  - lambda: 0.074679921357
01/07/2020 16:34:34  - Primal Variable Shape: (1, 602, 826)
01/07/2020 16:34:34  - Dual Variable Shape: (1, 602, 826)
01/07/2020 16:34:34 ERROR: __init__() got an unexpected keyword argument 'max_value'
Traceback (most recent call last):
  File "./sf_deconvolve.py", line 264, in main
    run_script(log)
  File "./sf_deconvolve.py", line 169, in run_script
    results = run(data_noisy, psf_data, **vars(opts))
  File "/home/sean/sf_deconvolve/sf_deconvolve_lib/deconvolve.py", line 535, in run
    kwargs['optimisation'].iterate(max_iter=kwargs['n_iter'])
  File "build/bdist.linux-x86_64/egg/modopt/opt/algorithms.py", line 1129, in iterate
    self._run_alg(max_iter)
  File "build/bdist.linux-x86_64/egg/modopt/opt/algorithms.py", line 257, in _run_alg
    with ProgressBar(redirect_stdout=True, max_value=max_iter) as bar:
TypeError: __init__() got an unexpected keyword argument 'max_value'
```

**Comment by sfarrens** [comment]
Hi @mooneyse, 

1. Regarding: 

```
with ProgressBar(redirect_stdout=True, max_value=max_iter) as bar:
TypeError: __init__() got an unexpected keyword argument 'max_value'
```

What version of [Progressbar2](https://pypi.org/project/progressbar2/) do you have installed? I just ran a test with the latest version (`3.51.4`) and it the code ran without issues. Make sure you are not using [Progressbar](https://pypi.org/project/progressbar/). 

2. Regarding:

```
01/07/2020 16:34:25  - Mode: lowr
...
01/07/2020 16:34:34  - Primal Variable Shape: (1, 602, 826)
```

Note that low-rank regularisation won't work with a single image & PSF (see [Farrens et al. 2017](https://arxiv.org/abs/1703.02305) for details). Instead you may want to try using sparse regularisation (*i.e.* `--mode sparse`) and choosing an appropriate wavelet transform for your data (with `--wavelet_type`).

**Comment by mooneyse** [comment]
That's great, thanks for the prompt response. It was indeed `Progressbar2`. It was not installed for Python 2. As suggested I changed to sparse regulation. All is running well at the moment. I'll check out the paper now.
